### ISSUE TITLE
Client-side exception error when running

### ISSUE THREAD

**Issue by elihanani** [valosan/jojogpt#1]
On the website I am getting the following error:

`Application error: a client-side exception has occurred (see the browser console for more information).
`

**Comment by huksley** [comment]
Thank you for reporting this, I will fix this to produce correct error message soon.

Recently ChatGPT responses were nerfed (i.e. they don't produce anymore meaningful results citing websites) so it was a fun experiment while it lasted :)

What is your use-case? What are trying to find?

**Comment by huksley** [comment]
fixed
